
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `factominer`=list(
        `type`="article", 
        `author`="L\u00EA, S., Josse, J., Husson, F.", 
        `year`=2008, 
        `title`="FactoMineR: An R Package for Multivariate Analysis", 
        `publisher`="Journal of Statistical Software", 
        `volume`=25, 
        `issue`=1, 
        `pages`="1\u201318", 
        `url`="https://doi.org/10.18637/jss.v025.i01"), 
    `mfa`=list(
        `type`="article", 
        `author`="Escofier, B., Pag\u00E8s, J.", 
        `year`=1994, 
        `title`="Multiple factor analysis (AFMULT package)", 
        `publisher`="Computational Statistics & Data Analysis", 
        `volume`=18, 
        `issue`=1, 
        `pages`="121\u2013140", 
        `url`="https://doi.org/10.1016/0167-9473(94)90135-X"), 
    `explo`=list(
        `type`="book", 
        `author`="Husson, F., L\u00EA, S., Pag\u00E8s, J.", 
        `year`=2017, 
        `title`="Exploratory Multivariate Analysis by Example Using R, Second Edition", 
        `publisher`="CRC Press", 
        `url`="https://www.routledge.com/Exploratory-Multivariate-Analysis-by-Example-Using-R/Husson-Le-Pages/p/book/9780367658021"))
