
# This file is automatically generated, you probably don't want to edit this

catdesOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "catdesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vartochar = NULL,
            descbyvar = NULL,
            threshold = 0.05, ...) {

            super$initialize(
                package='MEDA',
                name='catdes',
                requiresData=TRUE,
                ...)

            private$..vartochar <- jmvcore::OptionVariable$new(
                "vartochar",
                vartochar,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..descbyvar <- jmvcore::OptionVariables$new(
                "descbyvar",
                descbyvar,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..threshold <- jmvcore::OptionNumber$new(
                "threshold",
                threshold,
                default=0.05)

            self$.addOption(private$..vartochar)
            self$.addOption(private$..descbyvar)
            self$.addOption(private$..threshold)
        }),
    active = list(
        vartochar = function() private$..vartochar$value,
        descbyvar = function() private$..descbyvar$value,
        threshold = function() private$..threshold$value),
    private = list(
        ..vartochar = NA,
        ..descbyvar = NA,
        ..threshold = NA)
)

catdesResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        chigroup = function() private$.items[["chigroup"]],
        categgroup = function() private$.items[["categgroup"]],
        qtvargroup = function() private$.items[["qtvargroup"]],
        qtgroup = function() private$.items[["qtgroup"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Results of the Categorical variable description")
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    chi = function() private$.items[["chi"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="chigroup",
                            title="Chi-squared test")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="chi",
                            title="Link between the cluster variable and the categorical variables",
                            columns=list(
                                list(
                                    `name`="varchi", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="chipv", 
                                    `title`="p-value", 
                                    `type`="number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="integer"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    categ = function() private$.items[["categ"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="categgroup",
                            title="Description by the categorical variables")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="categ",
                            title="Description of each cluster by the categories",
                            columns=list(
                                list(
                                    `name`="varcateg", 
                                    `title`="", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="vardesccateg", 
                                    `title`="Category", 
                                    `type`="text"),
                                list(
                                    `name`="clamod", 
                                    `title`="Cla/Mod", 
                                    `type`="number"),
                                list(
                                    `name`="modcla", 
                                    `title`="Mod/Cla", 
                                    `type`="number"),
                                list(
                                    `name`="global", 
                                    `title`="Global", 
                                    `type`="number"),
                                list(
                                    `name`="categpv", 
                                    `title`="p-value", 
                                    `type`="number", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="vtest", 
                                    `title`="Vtest", 
                                    `type`="number"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    qtvar = function() private$.items[["qtvar"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="qtvargroup",
                            title="Global description by the quantitative variables")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="qtvar",
                            title="Link between the cluster variable and the quantitative variables",
                            columns=list(
                                list(
                                    `name`="varqtvar", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="scc", 
                                    `title`="Square correlation coefficient", 
                                    `type`="number"),
                                list(
                                    `name`="qtvarpv", 
                                    `title`="p-value", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    qt = function() private$.items[["qt"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="qtgroup",
                            title="Description by the quantitative variables")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="qt",
                            title="Description of each cluster by the quantative variables",
                            columns=list(
                                list(
                                    `name`="varqt", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="vardescqt", 
                                    `title`="Variable", 
                                    `type`="text"),
                                list(
                                    `name`="vtestqt", 
                                    `title`="Vtest", 
                                    `type`="number"),
                                list(
                                    `name`="meancateg", 
                                    `title`="Mean in category", 
                                    `type`="number"),
                                list(
                                    `name`="overallmean", 
                                    `title`="Overall mean", 
                                    `type`="number"),
                                list(
                                    `name`="sdcateg", 
                                    `title`="sd in category", 
                                    `type`="number"),
                                list(
                                    `name`="overallsd", 
                                    `title`="Overall sd", 
                                    `type`="number"),
                                list(
                                    `name`="qtpv", 
                                    `title`="p-value", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))}))

catdesBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "catdesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MEDA',
                name = 'catdes',
                version = c(1,0,0),
                options = options,
                results = catdesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Categorical variable described by Categorical / Quantitative data
#'
#' 
#' @param data .
#' @param vartochar .
#' @param descbyvar .
#' @param threshold .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$chigroup$chi} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$categgroup$categ} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$qtvargroup$qtvar} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$qtgroup$qt} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' @export
catdes <- function(
    data,
    vartochar,
    descbyvar,
    threshold = 0.05) {

    if ( ! requireNamespace('jmvcore'))
        stop('catdes requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vartochar)) vartochar <- jmvcore::resolveQuo(jmvcore::enquo(vartochar))
    if ( ! missing(descbyvar)) descbyvar <- jmvcore::resolveQuo(jmvcore::enquo(descbyvar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vartochar), vartochar, NULL),
            `if`( ! missing(descbyvar), descbyvar, NULL))

    for (v in vartochar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- catdesOptions$new(
        vartochar = vartochar,
        descbyvar = descbyvar,
        threshold = threshold)

    analysis <- catdesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
