
# This file is automatically generated, you probably don't want to edit this

descfreqOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "descfreqOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            columns = NULL,
            threshold = 0.05,
            coldesc = FALSE, ...) {

            super$initialize(
                package="MEDA",
                name="descfreq",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..columns <- jmvcore::OptionVariables$new(
                "columns",
                columns,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..threshold <- jmvcore::OptionNumber$new(
                "threshold",
                threshold,
                default=0.05)
            private$..coldesc <- jmvcore::OptionBool$new(
                "coldesc",
                coldesc,
                default=FALSE)

            self$.addOption(private$..rows)
            self$.addOption(private$..columns)
            self$.addOption(private$..threshold)
            self$.addOption(private$..coldesc)
        }),
    active = list(
        rows = function() private$..rows$value,
        columns = function() private$..columns$value,
        threshold = function() private$..threshold$value,
        coldesc = function() private$..coldesc$value),
    private = list(
        ..rows = NA,
        ..columns = NA,
        ..threshold = NA,
        ..coldesc = NA)
)

descfreqResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "descfreqResults",
    inherit = jmvcore::Group,
    active = list(
        descoftable = function() private$.items[["descoftable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Description of the Contingency Table")
            self$add(jmvcore::Table$new(
                options=options,
                name="descoftable",
                title="",
                visible="(rows)",
                columns=list(
                    list(
                        `name`="mod", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="rowcol", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="intern", 
                        `title`="Intern %", 
                        `type`="number"),
                    list(
                        `name`="glob", 
                        `title`="Glob %", 
                        `type`="number"),
                    list(
                        `name`="intfreq", 
                        `title`="Intern freq", 
                        `type`="number"),
                    list(
                        `name`="globfreq", 
                        `title`="Glob freq", 
                        `type`="number"),
                    list(
                        `name`="pvalue", 
                        `title`="p.value", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="vtest", 
                        `title`="v.test", 
                        `type`="number"))))}))

descfreqBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "descfreqBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MEDA",
                name = "descfreq",
                version = c(1,0,0),
                options = options,
                results = descfreqResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Description of a Contingency Table
#'
#' 
#' @param data .
#' @param rows .
#' @param columns .
#' @param threshold .
#' @param coldesc .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$descoftable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$descoftable$asDF}
#'
#' \code{as.data.frame(results$descoftable)}
#'
#' @export
descfreq <- function(
    data,
    rows,
    columns,
    threshold = 0.05,
    coldesc = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("descfreq requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(columns)) columns <- jmvcore::resolveQuo(jmvcore::enquo(columns))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(columns), columns, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- descfreqOptions$new(
        rows = rows,
        columns = columns,
        threshold = threshold,
        coldesc = coldesc)

    analysis <- descfreqClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

