
# This file is automatically generated, you probably don't want to edit this

MFAOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MFAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            quantivar = NULL,
            qualivar = NULL,
            individus = NULL,
            nFactors = 2,
            groupdef = "Ex: 2,3",
            groupill = "Ex: 2,3",
            groupname = "Ex: senso,physico",
            grouptype = "Ex: s,n",
            proba = 5,
            abs = 1,
            ord = 2,
            contivar = FALSE,
            catevar = FALSE, ...) {

            super$initialize(
                package="MEDA",
                name="MFA",
                requiresData=TRUE,
                ...)

            private$..quantivar <- jmvcore::OptionVariables$new(
                "quantivar",
                quantivar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..qualivar <- jmvcore::OptionVariables$new(
                "qualivar",
                qualivar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..individus <- jmvcore::OptionVariable$new(
                "individus",
                individus,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..nFactors <- jmvcore::OptionInteger$new(
                "nFactors",
                nFactors,
                default=2)
            private$..groupdef <- jmvcore::OptionString$new(
                "groupdef",
                groupdef,
                default="Ex: 2,3")
            private$..groupill <- jmvcore::OptionString$new(
                "groupill",
                groupill,
                default="Ex: 2,3")
            private$..groupname <- jmvcore::OptionString$new(
                "groupname",
                groupname,
                default="Ex: senso,physico")
            private$..grouptype <- jmvcore::OptionString$new(
                "grouptype",
                grouptype,
                default="Ex: s,n")
            private$..proba <- jmvcore::OptionNumber$new(
                "proba",
                proba,
                default=5)
            private$..abs <- jmvcore::OptionInteger$new(
                "abs",
                abs,
                default=1)
            private$..ord <- jmvcore::OptionInteger$new(
                "ord",
                ord,
                default=2)
            private$..contivar <- jmvcore::OptionBool$new(
                "contivar",
                contivar,
                default=FALSE)
            private$..catevar <- jmvcore::OptionBool$new(
                "catevar",
                catevar,
                default=FALSE)
            private$..newvar <- jmvcore::OptionOutput$new(
                "newvar")

            self$.addOption(private$..quantivar)
            self$.addOption(private$..qualivar)
            self$.addOption(private$..individus)
            self$.addOption(private$..nFactors)
            self$.addOption(private$..groupdef)
            self$.addOption(private$..groupill)
            self$.addOption(private$..groupname)
            self$.addOption(private$..grouptype)
            self$.addOption(private$..proba)
            self$.addOption(private$..abs)
            self$.addOption(private$..ord)
            self$.addOption(private$..contivar)
            self$.addOption(private$..catevar)
            self$.addOption(private$..newvar)
        }),
    active = list(
        quantivar = function() private$..quantivar$value,
        qualivar = function() private$..qualivar$value,
        individus = function() private$..individus$value,
        nFactors = function() private$..nFactors$value,
        groupdef = function() private$..groupdef$value,
        groupill = function() private$..groupill$value,
        groupname = function() private$..groupname$value,
        grouptype = function() private$..grouptype$value,
        proba = function() private$..proba$value,
        abs = function() private$..abs$value,
        ord = function() private$..ord$value,
        contivar = function() private$..contivar$value,
        catevar = function() private$..catevar$value,
        newvar = function() private$..newvar$value),
    private = list(
        ..quantivar = NA,
        ..qualivar = NA,
        ..individus = NA,
        ..nFactors = NA,
        ..groupdef = NA,
        ..groupill = NA,
        ..groupname = NA,
        ..grouptype = NA,
        ..proba = NA,
        ..abs = NA,
        ..ord = NA,
        ..contivar = NA,
        ..catevar = NA,
        ..newvar = NA)
)

MFAResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MFAResults",
    inherit = jmvcore::Group,
    active = list(
        plotgroup = function() private$.items[["plotgroup"]],
        plotaxe = function() private$.items[["plotaxe"]],
        plotind = function() private$.items[["plotind"]],
        plotvar = function() private$.items[["plotvar"]],
        eigengroup = function() private$.items[["eigengroup"]],
        descdesdim = function() private$.items[["descdesdim"]],
        newvar = function() private$.items[["newvar"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Results of the Multiple Factor Analysis")
            self$add(jmvcore::Image$new(
                options=options,
                name="plotgroup",
                title="Representation of the Groups",
                width=600,
                height=600,
                renderFun=".plotgroups"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotaxe",
                title="Representation of the Partial Axes",
                width=600,
                height=600,
                renderFun=".plotaxes"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotind",
                title="Representation of the Individuals (and the Categories)",
                width=800,
                height=600,
                renderFun=".plotindividus"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotvar",
                visible="(contivar)",
                title="Representation of the Variables",
                width=600,
                height=600,
                renderFun=".plotvariables"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    eigen = function() private$.items[["eigen"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="eigengroup",
                            title="Eigenvalue Decomposition")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="eigen",
                            title="Eigenvalue and (Cumulative) Percentage of Variance",
                            columns=list(
                                list(
                                    `name`="component", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="eigenvalue", 
                                    `title`="Eigenvalue", 
                                    `type`="number"),
                                list(
                                    `name`="purcent", 
                                    `title`="% of the variance", 
                                    `type`="number"),
                                list(
                                    `name`="purcentcum", 
                                    `title`="Cumulative %", 
                                    `type`="number"))))}))$new(options=options))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="descdesdim",
                title="Automatic Description of the Axes"))
            self$add(jmvcore::Output$new(
                options=options,
                name="newvar",
                title="Coordinates",
                measureType="continuous",
                initInRun=TRUE,
                clearWith=list(
                    "actvars",
                    "quantisup",
                    "qualisup",
                    "individus",
                    "nFactors",
                    "norme")))}))

MFABase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MFABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MEDA",
                name = "MFA",
                version = c(1,0,0),
                options = options,
                results = MFAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Multiple Factor Analysis
#'
#' 
#' @param data .
#' @param quantivar .
#' @param qualivar .
#' @param individus .
#' @param nFactors .
#' @param groupdef .
#' @param groupill .
#' @param groupname .
#' @param grouptype .
#' @param proba .
#' @param abs .
#' @param ord .
#' @param contivar .
#' @param catevar .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plotgroup} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotaxe} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotind} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotvar} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$eigengroup$eigen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$descdesdim} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$newvar} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
MFA <- function(
    data,
    quantivar,
    qualivar,
    individus,
    nFactors = 2,
    groupdef = "Ex: 2,3",
    groupill = "Ex: 2,3",
    groupname = "Ex: senso,physico",
    grouptype = "Ex: s,n",
    proba = 5,
    abs = 1,
    ord = 2,
    contivar = FALSE,
    catevar = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("MFA requires jmvcore to be installed (restart may be required)")

    if ( ! missing(quantivar)) quantivar <- jmvcore::resolveQuo(jmvcore::enquo(quantivar))
    if ( ! missing(qualivar)) qualivar <- jmvcore::resolveQuo(jmvcore::enquo(qualivar))
    if ( ! missing(individus)) individus <- jmvcore::resolveQuo(jmvcore::enquo(individus))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(quantivar), quantivar, NULL),
            `if`( ! missing(qualivar), qualivar, NULL),
            `if`( ! missing(individus), individus, NULL))

    for (v in qualivar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in individus) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- MFAOptions$new(
        quantivar = quantivar,
        qualivar = qualivar,
        individus = individus,
        nFactors = nFactors,
        groupdef = groupdef,
        groupill = groupill,
        groupname = groupname,
        grouptype = grouptype,
        proba = proba,
        abs = abs,
        ord = ord,
        contivar = contivar,
        catevar = catevar)

    analysis <- MFAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

