
# This file is automatically generated, you probably don't want to edit this

PCAOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "PCAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            actvars = NULL,
            quantisup = NULL,
            qualisup = NULL,
            individus = NULL,
            nFactors = 5,
            norme = TRUE,
            coordvar = FALSE,
            contribvar = FALSE,
            cosvar = FALSE,
            coordind = FALSE,
            contribind = FALSE,
            cosind = FALSE,
            proba = 0.05,
            abs = 1,
            ord = 2,
            varact = TRUE,
            varillus = TRUE,
            modact = TRUE,
            modillus = TRUE,
            habillage = NULL, ...) {

            super$initialize(
                package='MEDA',
                name='PCA',
                requiresData=TRUE,
                ...)

            private$..actvars <- jmvcore::OptionVariables$new(
                "actvars",
                actvars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..quantisup <- jmvcore::OptionVariables$new(
                "quantisup",
                quantisup,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..qualisup <- jmvcore::OptionVariables$new(
                "qualisup",
                qualisup,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..individus <- jmvcore::OptionVariable$new(
                "individus",
                individus,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..nFactors <- jmvcore::OptionInteger$new(
                "nFactors",
                nFactors,
                default=5)
            private$..norme <- jmvcore::OptionBool$new(
                "norme",
                norme,
                default=TRUE)
            private$..coordvar <- jmvcore::OptionBool$new(
                "coordvar",
                coordvar,
                default=FALSE)
            private$..contribvar <- jmvcore::OptionBool$new(
                "contribvar",
                contribvar,
                default=FALSE)
            private$..cosvar <- jmvcore::OptionBool$new(
                "cosvar",
                cosvar,
                default=FALSE)
            private$..coordind <- jmvcore::OptionBool$new(
                "coordind",
                coordind,
                default=FALSE)
            private$..contribind <- jmvcore::OptionBool$new(
                "contribind",
                contribind,
                default=FALSE)
            private$..cosind <- jmvcore::OptionBool$new(
                "cosind",
                cosind,
                default=FALSE)
            private$..proba <- jmvcore::OptionNumber$new(
                "proba",
                proba,
                default=0.05)
            private$..abs <- jmvcore::OptionInteger$new(
                "abs",
                abs,
                default=1)
            private$..ord <- jmvcore::OptionInteger$new(
                "ord",
                ord,
                default=2)
            private$..varact <- jmvcore::OptionBool$new(
                "varact",
                varact,
                default=TRUE)
            private$..varillus <- jmvcore::OptionBool$new(
                "varillus",
                varillus,
                default=TRUE)
            private$..modact <- jmvcore::OptionBool$new(
                "modact",
                modact,
                default=TRUE)
            private$..modillus <- jmvcore::OptionBool$new(
                "modillus",
                modillus,
                default=TRUE)
            private$..habillage <- jmvcore::OptionInteger$new(
                "habillage",
                habillage)

            self$.addOption(private$..actvars)
            self$.addOption(private$..quantisup)
            self$.addOption(private$..qualisup)
            self$.addOption(private$..individus)
            self$.addOption(private$..nFactors)
            self$.addOption(private$..norme)
            self$.addOption(private$..coordvar)
            self$.addOption(private$..contribvar)
            self$.addOption(private$..cosvar)
            self$.addOption(private$..coordind)
            self$.addOption(private$..contribind)
            self$.addOption(private$..cosind)
            self$.addOption(private$..proba)
            self$.addOption(private$..abs)
            self$.addOption(private$..ord)
            self$.addOption(private$..varact)
            self$.addOption(private$..varillus)
            self$.addOption(private$..modact)
            self$.addOption(private$..modillus)
            self$.addOption(private$..habillage)
        }),
    active = list(
        actvars = function() private$..actvars$value,
        quantisup = function() private$..quantisup$value,
        qualisup = function() private$..qualisup$value,
        individus = function() private$..individus$value,
        nFactors = function() private$..nFactors$value,
        norme = function() private$..norme$value,
        coordvar = function() private$..coordvar$value,
        contribvar = function() private$..contribvar$value,
        cosvar = function() private$..cosvar$value,
        coordind = function() private$..coordind$value,
        contribind = function() private$..contribind$value,
        cosind = function() private$..cosind$value,
        proba = function() private$..proba$value,
        abs = function() private$..abs$value,
        ord = function() private$..ord$value,
        varact = function() private$..varact$value,
        varillus = function() private$..varillus$value,
        modact = function() private$..modact$value,
        modillus = function() private$..modillus$value,
        habillage = function() private$..habillage$value),
    private = list(
        ..actvars = NA,
        ..quantisup = NA,
        ..qualisup = NA,
        ..individus = NA,
        ..nFactors = NA,
        ..norme = NA,
        ..coordvar = NA,
        ..contribvar = NA,
        ..cosvar = NA,
        ..coordind = NA,
        ..contribind = NA,
        ..cosind = NA,
        ..proba = NA,
        ..abs = NA,
        ..ord = NA,
        ..varact = NA,
        ..varillus = NA,
        ..modact = NA,
        ..modillus = NA,
        ..habillage = NA)
)

PCAResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        plotind = function() private$.items[["plotind"]],
        plotvar = function() private$.items[["plotvar"]],
        eigengroup = function() private$.items[["eigengroup"]],
        descdesdim = function() private$.items[["descdesdim"]],
        individus = function() private$.items[["individus"]],
        variables = function() private$.items[["variables"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Results of the Principal Component Analysis")
            self$add(jmvcore::Image$new(
                options=options,
                name="plotind",
                title="Representation of the individuals (and the categories)",
                width=800,
                height=600,
                renderFun=".plotindividus"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotvar",
                title="Representation of the variables",
                width=600,
                height=600,
                renderFun=".plotvariables"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    eigen = function() private$.items[["eigen"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="eigengroup",
                            title="Eigenvalue decomposition")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="eigen",
                            title="Eigenvalue and (cumulative) percentage of variance",
                            columns=list(
                                list(
                                    `name`="component", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="eigenvalue", 
                                    `title`="Eigenvalue", 
                                    `type`="number"),
                                list(
                                    `name`="purcent", 
                                    `title`="% of the variance", 
                                    `type`="number"),
                                list(
                                    `name`="purcentcum", 
                                    `title`="Cumulative %", 
                                    `type`="number"))))}))$new(options=options))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="descdesdim",
                title="Automatic description of the axes"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    coordonnees = function() private$.items[["coordonnees"]],
                    contribution = function() private$.items[["contribution"]],
                    cosinus = function() private$.items[["cosinus"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="individus",
                            title="Individual tables")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="coordonnees",
                            title="Coordinates table",
                            visible="(coordind)",
                            clearWith=list(
                                "nFactors"),
                            columns=list()))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="contribution",
                            title="Contributions table",
                            visible="(contribind)",
                            clearWith=list(
                                "nFactors"),
                            columns=list()))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="cosinus",
                            title="Cosinus table",
                            visible="(cosind)",
                            clearWith=list(
                                "nFactors"),
                            columns=list()))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    coordonnees = function() private$.items[["coordonnees"]],
                    contribution = function() private$.items[["contribution"]],
                    cosinus = function() private$.items[["cosinus"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="variables",
                            title="Variable tables")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="coordonnees",
                            title="Coordinates table",
                            visible="(coordvar)",
                            clearWith=list(
                                "nFactors"),
                            columns=list()))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="contribution",
                            title="Contributions table",
                            visible="(contribvar)",
                            clearWith=list(
                                "nFactors"),
                            columns=list()))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="cosinus",
                            title="Cosinus table",
                            visible="(cosvar)",
                            clearWith=list(
                                "nFactors"),
                            columns=list()))}))$new(options=options))}))

PCABase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "PCABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MEDA',
                name = 'PCA',
                version = c(1,0,0),
                options = options,
                results = PCAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Principal Component Analysis
#'
#' 
#' @param data .
#' @param actvars .
#' @param quantisup .
#' @param qualisup .
#' @param individus .
#' @param nFactors .
#' @param norme .
#' @param coordvar .
#' @param contribvar .
#' @param cosvar .
#' @param coordind .
#' @param contribind .
#' @param cosind .
#' @param proba .
#' @param abs .
#' @param ord .
#' @param varact .
#' @param varillus .
#' @param modact .
#' @param modillus .
#' @param habillage .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plotind} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotvar} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$eigengroup$eigen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$descdesdim} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$individus$coordonnees} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$individus$contribution} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$individus$cosinus} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$variables$coordonnees} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$variables$contribution} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$variables$cosinus} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' @export
PCA <- function(
    data,
    actvars,
    quantisup,
    qualisup,
    individus,
    nFactors = 5,
    norme = TRUE,
    coordvar = FALSE,
    contribvar = FALSE,
    cosvar = FALSE,
    coordind = FALSE,
    contribind = FALSE,
    cosind = FALSE,
    proba = 0.05,
    abs = 1,
    ord = 2,
    varact = TRUE,
    varillus = TRUE,
    modact = TRUE,
    modillus = TRUE,
    habillage) {

    if ( ! requireNamespace('jmvcore'))
        stop('PCA requires jmvcore to be installed (restart may be required)')

    if ( ! missing(actvars)) actvars <- jmvcore::resolveQuo(jmvcore::enquo(actvars))
    if ( ! missing(quantisup)) quantisup <- jmvcore::resolveQuo(jmvcore::enquo(quantisup))
    if ( ! missing(qualisup)) qualisup <- jmvcore::resolveQuo(jmvcore::enquo(qualisup))
    if ( ! missing(individus)) individus <- jmvcore::resolveQuo(jmvcore::enquo(individus))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(actvars), actvars, NULL),
            `if`( ! missing(quantisup), quantisup, NULL),
            `if`( ! missing(qualisup), qualisup, NULL),
            `if`( ! missing(individus), individus, NULL))

    for (v in qualisup) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in individus) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- PCAOptions$new(
        actvars = actvars,
        quantisup = quantisup,
        qualisup = qualisup,
        individus = individus,
        nFactors = nFactors,
        norme = norme,
        coordvar = coordvar,
        contribvar = contribvar,
        cosvar = cosvar,
        coordind = coordind,
        contribind = contribind,
        cosind = cosind,
        proba = proba,
        abs = abs,
        ord = ord,
        varact = varact,
        varillus = varillus,
        modact = modact,
        modillus = modillus,
        habillage = habillage)

    analysis <- PCAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
