
# This file is automatically generated, you probably don't want to edit this

textualOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "textualOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            individuals = NULL,
            words = NULL,
            checkboxtextual = TRUE,
            checkboxchideux = TRUE,
            checkboxdf = TRUE,
            thres = 0.05, ...) {

            super$initialize(
                package='MEDA',
                name='textual',
                requiresData=TRUE,
                ...)

            private$..individuals <- jmvcore::OptionVariable$new(
                "individuals",
                individuals)
            private$..words <- jmvcore::OptionVariable$new(
                "words",
                words)
            private$..checkboxtextual <- jmvcore::OptionBool$new(
                "checkboxtextual",
                checkboxtextual,
                default=TRUE)
            private$..checkboxchideux <- jmvcore::OptionBool$new(
                "checkboxchideux",
                checkboxchideux,
                default=TRUE)
            private$..checkboxdf <- jmvcore::OptionBool$new(
                "checkboxdf",
                checkboxdf,
                default=TRUE)
            private$..thres <- jmvcore::OptionNumber$new(
                "thres",
                thres,
                default=0.05)

            self$.addOption(private$..individuals)
            self$.addOption(private$..words)
            self$.addOption(private$..checkboxtextual)
            self$.addOption(private$..checkboxchideux)
            self$.addOption(private$..checkboxdf)
            self$.addOption(private$..thres)
        }),
    active = list(
        individuals = function() private$..individuals$value,
        words = function() private$..words$value,
        checkboxtextual = function() private$..checkboxtextual$value,
        checkboxchideux = function() private$..checkboxchideux$value,
        checkboxdf = function() private$..checkboxdf$value,
        thres = function() private$..thres$value),
    private = list(
        ..individuals = NA,
        ..words = NA,
        ..checkboxtextual = NA,
        ..checkboxchideux = NA,
        ..checkboxdf = NA,
        ..thres = NA)
)

textualResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        textualgroup = function() private$.items[["textualgroup"]],
        chideuxgroup = function() private$.items[["chideuxgroup"]],
        dfresgroup = function() private$.items[["dfresgroup"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Results of the Categorical variable description")
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    textual = function() private$.items[["textual"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="textualgroup",
                            title="Textual Data Analysis")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="textual",
                            title="Contingency table",
                            visible="(checkboxtextual)",
                            clearWith=list(
                                "individuals",
                                "words"),
                            columns=list()))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    chideux = function() private$.items[["chideux"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="chideuxgroup",
                            title="Chi-squared test")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="chideux",
                            title="Pearson's Chi-squared test",
                            visible="(checkboxchideux)",
                            clearWith=list(
                                "individuals",
                                "words"),
                            rows=1,
                            columns=list(
                                list(
                                    `name`="value", 
                                    `title`="X-squared", 
                                    `type`="Integer"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="Integer"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p-value", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    dfres = function() private$.items[["dfres"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="dfresgroup",
                            title="Description of frequencies")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="dfres",
                            title="Description of the rows of the contingency table",
                            visible="(checkboxdf)",
                            columns=list(
                                list(
                                    `name`="component", 
                                    `title`="", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="word", 
                                    `title`="Word", 
                                    `type`="text"),
                                list(
                                    `name`="internper", 
                                    `title`="Intern %", 
                                    `type`="Number"),
                                list(
                                    `name`="globper", 
                                    `title`="Global %", 
                                    `type`="Number"),
                                list(
                                    `name`="internfreq", 
                                    `title`="Intern frequency", 
                                    `type`="Number"),
                                list(
                                    `name`="globfreq", 
                                    `title`="Global frequency", 
                                    `type`="Number"),
                                list(
                                    `name`="pvaluedfres", 
                                    `title`="p-value", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="vtest", 
                                    `title`="Vtest", 
                                    `type`="Number"))))}))$new(options=options))}))

textualBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "textualBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MEDA',
                name = 'textual',
                version = c(1,0,0),
                options = options,
                results = textualResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Categorical variable described by Textual data
#'
#' 
#' @param data .
#' @param individuals .
#' @param words .
#' @param checkboxtextual .
#' @param checkboxchideux .
#' @param checkboxdf .
#' @param thres .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$textualgroup$textual} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$chideuxgroup$chideux} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dfresgroup$dfres} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' @export
textual <- function(
    data,
    individuals,
    words,
    checkboxtextual = TRUE,
    checkboxchideux = TRUE,
    checkboxdf = TRUE,
    thres = 0.05) {

    if ( ! requireNamespace('jmvcore'))
        stop('textual requires jmvcore to be installed (restart may be required)')

    if ( ! missing(individuals)) individuals <- jmvcore::resolveQuo(jmvcore::enquo(individuals))
    if ( ! missing(words)) words <- jmvcore::resolveQuo(jmvcore::enquo(words))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(individuals), individuals, NULL),
            `if`( ! missing(words), words, NULL))


    options <- textualOptions$new(
        individuals = individuals,
        words = words,
        checkboxtextual = checkboxtextual,
        checkboxchideux = checkboxchideux,
        checkboxdf = checkboxdf,
        thres = thres)

    analysis <- textualClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
