
# This file is automatically generated, you probably don't want to edit this

textualOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "textualOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            individuals = NULL,
            words = NULL,
            thres = 0.05, ...) {

            super$initialize(
                package="MEDA",
                name="textual",
                requiresData=TRUE,
                ...)

            private$..individuals <- jmvcore::OptionVariable$new(
                "individuals",
                individuals,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..words <- jmvcore::OptionVariable$new(
                "words",
                words)
            private$..thres <- jmvcore::OptionNumber$new(
                "thres",
                thres,
                default=0.05)

            self$.addOption(private$..individuals)
            self$.addOption(private$..words)
            self$.addOption(private$..thres)
        }),
    active = list(
        individuals = function() private$..individuals$value,
        words = function() private$..words$value,
        thres = function() private$..thres$value),
    private = list(
        ..individuals = NA,
        ..words = NA,
        ..thres = NA)
)

textualResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "textualResults",
    inherit = jmvcore::Group,
    active = list(
        textualgroup = function() private$.items[["textualgroup"]],
        chideuxgroup = function() private$.items[["chideuxgroup"]],
        dfresgroup = function() private$.items[["dfresgroup"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Results of the Categorical Variable Description")
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    textual = function() private$.items[["textual"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="textualgroup",
                            title="Textual Data Analysis")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="textual",
                            title="Contingency Table",
                            visible="(individuals)",
                            clearWith=list(
                                "individuals",
                                "words"),
                            columns=list()))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    chideux = function() private$.items[["chideux"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="chideuxgroup",
                            title="Chi-Squared Test")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="chideux",
                            title="Pearson's Chi-Squared Test",
                            visible="(individuals)",
                            clearWith=list(
                                "individuals",
                                "words"),
                            rows=1,
                            columns=list(
                                list(
                                    `name`="value", 
                                    `title`="X-squared", 
                                    `type`="Integer"),
                                list(
                                    `name`="df", 
                                    `title`="df", 
                                    `type`="Integer"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p-value", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    dfres = function() private$.items[["dfres"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="dfresgroup",
                            title="Description of Frequencies")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="dfres",
                            title="Description of the Rows of the Contingency Table",
                            visible="(individuals)",
                            columns=list(
                                list(
                                    `name`="component", 
                                    `title`="", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="word", 
                                    `title`="Word", 
                                    `type`="text"),
                                list(
                                    `name`="internper", 
                                    `title`="Intern %", 
                                    `type`="Number"),
                                list(
                                    `name`="globper", 
                                    `title`="Global %", 
                                    `type`="Number"),
                                list(
                                    `name`="internfreq", 
                                    `title`="Intern frequency", 
                                    `type`="Number"),
                                list(
                                    `name`="globfreq", 
                                    `title`="Global frequency", 
                                    `type`="Number"),
                                list(
                                    `name`="pvaluedfres", 
                                    `title`="p-value", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="vtest", 
                                    `title`="Vtest", 
                                    `type`="Number"))))}))$new(options=options))}))

textualBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "textualBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MEDA",
                name = "textual",
                version = c(1,0,0),
                options = options,
                results = textualResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Categorical Variable Described by Textual Data
#'
#' 
#' @param data .
#' @param individuals .
#' @param words .
#' @param thres .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$textualgroup$textual} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$chideuxgroup$chideux} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dfresgroup$dfres} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' @export
textual <- function(
    data,
    individuals,
    words,
    thres = 0.05) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("textual requires jmvcore to be installed (restart may be required)")

    if ( ! missing(individuals)) individuals <- jmvcore::resolveQuo(jmvcore::enquo(individuals))
    if ( ! missing(words)) words <- jmvcore::resolveQuo(jmvcore::enquo(words))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(individuals), individuals, NULL),
            `if`( ! missing(words), words, NULL))

    for (v in individuals) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- textualOptions$new(
        individuals = individuals,
        words = words,
        thres = thres)

    analysis <- textualClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

